### ISSUE TITLE
Vulcan Shaper binary

### ISSUE THREAD

**Issue by Kethku** [rust-skia/skia-binaries#1]
I'm interested in using the rust-skia project via skulper in a project I am working on. Unfortunately I would like to use the harfbuzz wrapper in skia but it looks like there are no binaries for windows which contain both the vulcan and shaper features. Further for some reason I can't build the project locally. I run into strange errors and after looking at the dependencies I'm not sure building the skia library locally is really an option.

Is there any way I could take advantage of the CI infrastructure already in place to build a shaper and vulcan enabled binary and use that? Thanks in advance either way!

**Comment by Kethku** [comment]
I looked at the pipelines and made what might be the necessary change in a PR which is linked above. I don't know how to test to see if this works though. Any help?

**Comment by Kethku** [comment]
Fixed by https://github.com/rust-skia/rust-skia/pull/227

**Comment by pragmatrix** [comment]
> I run into strange errors and after looking at the dependencies I'm not sure building the skia library locally is really an option.

I hope it's not too much to ask to run the build again and create an issue in the rust-skia repository  with the error messages attached. I'd really like to take a look.
